project:
  type: website
  output-dir: docs

website:
  title: "Futureverse"
  favicon: images/favicon.ico
  site-url: https://www.futureverse.org
  description: "Futureverse"
  google-analytics: "G-SB3EQSD9FR"

  navbar:
    logo:
      images/logo.png

    right:
      - text: "Packages & Docs"
        menu:
          - text: "Overview of All Packages"
            href: packages-overview.qmd
          - text: "---"
          - text: "Core Future API"
          - text: "future (core of the future framework)"
            href: https://future.futureverse.org
          - text: "---"
          - text: "Map-Reduce Future APIs"
          - text: "future.apply (base R apply with futures)"
            href: https://future.apply.futureverse.org
          - text: "furrr (purrr with futures)"
            href: https://furrr.futureverse.org
          - text: "doFuture (a foreach adapter)"
            href: https://doFuture.futureverse.org
          - text: "---"
          - text: "Parallel Backends"
          - text: "future (built-in, local & remote parallelization)"
            href: https://future.futureverse.org
          - text: "future.batchtools (use HPC scheduler)"
            href: https://future.batchtools.futureverse.org
          - text: "future.callr (local callr parallelization)"
            href: https://future.callr.futureverse.org
          - text: "future.mirai (parallelize via mirai)"
            href: https://future.mirai.futureverse.org
          - text: "---"
          - text: "Utilities"
          - text: "listenv (Use %<-% for list-like structures)"
            href: https://listenv.futureverse.org
          - text: "parallelly (enhances the parallel package)"
            href: https://parallelly.futureverse.org
          - text: "progressr (progress updates in parallel)"
            href: https://progressr.futureverse.org
          - text: "---"
          - text: "For low-level developers"
          - text: "globals (identify globals)"
            href: https://globals.futureverse.org
          - text: "future.tests (validate future backends)"
            href: https://future.tests.futureverse.org
          - text: "---"
          - text: "Experimental"
          - text: "future.tools (tools for working with futures)"
            href: https://future.tools.futureverse.org
          - text: "BiocParallel.FutureParam (a BiocParallel addon)"
            href: https://BiocParallel.FutureParam.futureverse.org/
          - text: "marshal (export non-exportable objects)"
            href: https://marshal.futureverse.org

      - text: "Parallel Backends"
        href: backends.qmd
        
      - text: "Tutorials"
        href: tutorials.qmd
        
      - text: "Talks"
        href: talks.qmd
        
      - text: "Use & Stats"
        href: usage.qmd
        
      - text: "Quality"
        href: quality.qmd
        
      - text: "Blog"
        href: blog.qmd
        
      - text: "Publications"
        href: publications.qmd
        
      - text: "Roadmap"
        href: roadmap.qmd
        
      - text: "About"
        href: about.qmd

format:
  html:
    toc: true
    respect-user-color-scheme: true
    
theme:
  light: flatly
  dark: darkly

filters:
  - spellcheck.lua
