---
title: About
description: Grew out of a need to analyze large-scale data
preview: images/site_preview.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## About the project lead

The project lead, Henrik Bengtsson, has a MSc in Computer Science and a PhD in Mathematical Statistics.  He is an associate professor at the Department of Epidemiology & Biostatistics, at University of California San Francisco (UCSF) and affiliated with the UCSF Helen Diller Family Comprehensive Cancer Center.

Henrik is one of forty members of the [R Foundation](https://www.r-project.org/foundation/) - a non-profit organization that supports the R Project, its continued development of the R language, and the R community around it.  Through this work, he is also a member of the [R Consortium Infrastructure Software Committee (ISC)](https://www.r-consortium.org/projects), which supports research & development activities related to R through a grant program with financial support from leading industry investors.

He has developed small and large-scale scientific software for 25 years within areas of statistics, bioinformatics, genomics, cancer research, and computational sciences.  These tools have been developed as part of real-world collaborative research projects going from scientific question, to statistical models and estimators, and implementation and validation.  It is throughout the computational needs of these small and large-scale projects that the seed to what would become the future ecosystem sprung out.

Henrik has worked with R since 2000 and has contributed with many R packages on CRAN and Bioconductor.  With [more than 30 CRAN packages](https://r-pkg.org/maint/henrikb@braju.com), he is among the top-10 maintainers there.  Several of his packages are among the top-1% most downloaded on CRAN.  He has also developed and contributed to several Bioconductor packages.  He has also contributed with design and implementation to the R core distribution.

Open access, open source, cross-platform operability, long-term stability, correctness, and reproducibility are absolute top priorities throughout all his software projects.

