---
title: Blog Posts
description: Updates, tips & tricks, and explanations on futures
preview: images/site_preview.png
---

* [Using Kubernetes and the Future Package to Easily Parallelize R in the Cloud ](https://www.jottr.org/2021/04/08/future-and-kubernetes/), jottr.org, 2021-04-08  
  _Guest post by Chris Paciorek, Department of Statistics, University of California at Berkeley_

* [future.BatchJobs - End-of-Life Announcement](https://www.jottr.org/2021/01/08/future.batchjobs-end-of-life-announcement/), jottr.org, 2021-01-08

* [future 1.20.1 - The Future Just Got a Bit Brighter](https://www.jottr.org/2020/11/06/future-1.20.1-the-future-just-got-a-bit-brighter/), jottr.org, 2020-11-06

* [parallelly, future - Cleaning Up Around the House](https://www.jottr.org/2020/11/04/parallelly-future-cleaning-up-around-the-house/), jottr.org, 2020-11-04

* [Trust the Future](https://www.jottr.org/2020/11/04/trust-the-future/), jottr.org, 2020-11-04

* [future 1.19.1 - Making Sure Proper Random Numbers are Produced in Parallel Processing](https://www.jottr.org/2020/09/22/push-for-statical-sound-rng/), jottr.org, 2020-09-22

* [Detect When the Random Number Generator Was Used](https://www.jottr.org/2020/09/21/detect-when-the-random-number-generator-was-used/), jottr.org, 2020-09-21

* [future and future.apply - Some Recent Improvements](https://www.jottr.org/2020/07/11/future-future.apply-recent-improvements/), jottr.org, 2020-07-11

* [future 1.15.0 - Lazy Futures are Now Launched if Queried](https://www.jottr.org/2019/11/09/resolved-launches-lazy-futures/), jottr.org, 2019-11-09

* [Parallelize a For-Loop by Rewriting it as an Lapply Call ](https://www.jottr.org/2019/01/11/parallelize-a-for-loop-by-rewriting-it-as-an-lapply-call/), jottr.org, 2019-01-11

* [Maintenance Updates of Future Backends and doFuture](https://www.jottr.org/2019/01/07/maintenance-updates-of-future-backends-and-dofuture/), jottr.org, 2019-01-07

* [future 1.9.0 - Output from The Future](https://www.jottr.org/2018/07/23/output-from-the-future/), jottr.org, 2018-07-23

* [future.apply - Parallelize Any Base R Apply Function](https://www.jottr.org/2018/06/23/future.apply_1.0.0/), jottr.org, 2018-06-23

* [future 1.8.0: Preparing for a Shiny Future](https://www.jottr.org/2018/04/12/future-results/), jottr.org, 2018-04-12

* [The Many-Faced Future](https://www.jottr.org/2017/06/05/many-faced-future/), jottr.org, 2017-06-05

* [doFuture: A Universal Foreach Adaptor Ready to be Used by 1,000+ Packages](https://www.jottr.org/2017/03/18/dofuture/), jottr.org, 2017-03-18

* [future 1.3.0: Reproducible RNGs, future_lapply() and More](https://www.jottr.org/2017/02/19/future-rng/), jottr.org, 2017-02-19

* [High-Performance Compute in R Using Futures ](https://www.jottr.org/2016/10/22/future-hpc/), jottr.org, 2016-10-22

* [Remote Processing Using Futures](https://www.jottr.org/2016/10/11/future-remotes/), jottr.org, 2016-10-11


