---
title: Talks
description: Presentations on futures with slides and recorded videos
preview: images/site_preview.png
---

* Henrik Bengtsson, [future.mirai: Use the Mirai Parallelization Framework in Futureverse - Easy!](https://henrikbengtsson.github.io/talk-user2024-future.mirai/#/), useR! 2024, Salzburg, Austria, 2024-07-09 (20 minutes) [[HTML](https://henrikbengtsson.github.io/talk-user2024-future.mirai/#/), [PDF](https://raw.githubusercontent.com/HenrikBengtsson/talk-user2024-future.mirai/main/BengtssonH_20240709-future.mirai-useR2024.pdf)]

* Henrik Bengtsson, [Futureverse - A Unifying Parallelization Framework in R for Everyone](https://www.jottr.org/2023/05/22/future-yegrug-2023-slides/), Edmonton R User Group Meetup (YEGRUG), 2023-05-22 (60 minutes)

* Henrik Bengtsson, [Futureverse: Profile Parallel Code](https://www.jottr.org/2022/06/23/future-user2022-slides/), useR! 2022, 2022-06-22 (25 minutes)

* Henrik Bengtsson, [Future - Simple, Scalable Parallelization in R for the Biomedical Community](https://docs.google.com/presentation/d/18gxBd5Bgn0GNDyl5MlCt_s7b6gTUEcJV9c2xSLC11Nk/view#slide=id.gf778290f24_0_165), CZI EOSS 2021, 2021-11-02 (10 minutes)

* Henrik Bengtsson, [Future: A Simple, Extendable, Generic Framework for Parallel Processing in R](https://www.jottr.org/2020/12/19/future-eurobioc2020-slides/), European Bioconductor Meeting 2020, 2020-12-19 (35 minutes)

* Henrik Bengtsson, [Future: Simple, Friendly Parallel Processing for R](https://www.jottr.org/2020/11/12/future-nycmeetup-slides/), New York Open Statistical Programming Meetup, 2020-11-12 (67 minutes)

* Henrik Bengtsson, [Progressr: An Inclusive, Unifying API for Progress Updates](https://www.jottr.org/2020/07/04/progressr-erum2020-slides/), e-Rum 2020, 2020-06-17 (15 minutes)

* Henrik Bengtsson, [Future: Simple Async, Parallel & Distributed Processing in R Why and What’s New?](https://www.jottr.org/2020/02/01/future-rstudioconf2020-slides/), rstudio::conf 2020, San Francisco, USA, 2020-01-29 (18 minutes)

* Henrik Bengtsson, [Future: Simple Parallel and Distributed Processing in R](https://www.jottr.org/2019/07/12/future-user2019-slides/), useR! 2019, Toulouse, France, 2019-07-12 (15 minutes)

* Henrik Bengtsson, [Future: Friendly Parallel Processing in R for Everyone](https://www.jottr.org/2019/05/16/future-satrdayla2019-slides/), satRday LA 2019, Los Angeles, USA, 2019-04-06 (45 minutes)

* Henrik Bengtsson, [Future: Friendly Parallel Processing in R for Everyone](https://www.jottr.org/2019/03/07/future-satrdayparis2019-slides/),  satRday Paris 2019, Paris, France, 2019-02-23 (40 minutes)

* Henrik Bengtsson, [Future: Parallel & Distributed Processing in R for Everyone](https://www.jottr.org/2018/06/18/future-erum2018-slides/), eRum 2018, Budapest, Hungary, 2018-05-16 (20 minutes)

* Henrik Bengtsson, [Futures in R: Atomic Building Blocks for Asynchronous Evaluation](https://wiki.r-consortium.org/view/Distributed_Computing_Working_Group#05.2F11.2F2017), R Consortium, Distributed Computing Working Group, 2017-05-11 (60 minutes)

* Henrik Bengtsson, [A Future for R](https://www.jottr.org/2016/07/02/future-user2016-slides/), useR! 2016, Stanford, USA, 2016-06-28 (18 minutes)

