---
title: Talks
description: Presentations on futures with slides and recorded videos
preview: images/site_preview.png
format:
  html:
    css: assets/custom.css
---

```{r}
#| include: false
talk <- function(title, author, info = NULL, location = NULL, duration = NULL, date, urls = NULL) {
  library(htmltools)
  html <- tags$div(class = "listItem",
    tags$div(class = "itemDetails",
      tags$div(class = "itemHeader",
        tags$div(class = "itemTitle", title)
      ),
      tags$div(class = "itemMeta",
        tags$span(class = "author", author),
        tags$span(class = "itemInfo", location),
        tags$span(class = "itemDate", sprintf("%s (%s)", date, duration))
      ),
      lapply(seq_along(urls), FUN = function(kk) {
        if (nzchar(urls[[kk]])) tags$a(href = urls[[kk]], names(urls)[kk])
      })
    )
  )
  knitr::asis_output(as.character(html))
} # talk()
```

```{r}
#| echo: false
talk(
     title = "Futureverse P2P: Peer-to-Peer Parallelization in R - Share compute among friends across the world",
    author = "Henrik Bengtsson",
  location = "useR! 2025, Durham, NC, USA",
      date = "2025-08-10",
  duration = "18 minutes",
      urls = c(HTML = "https://henrikbengtsson.github.io/talk-user2025-p2p/#/", PDF = "https://raw.githubusercontent.com/HenrikBengtsson/talk-user2025-p2p/main/BengtssonH_20240810-future.p2p-useR2025.pdf", Video = "https://www.youtube.com/watch?v=T0zbQp1hIEs", "Blog post" = "https://www.jottr.org/2025/08/14/future.p2p-user2025-slides/")
)
```


```{r}
#| echo: false
talk(
     title = "future.mirai: Use the Mirai Parallelization Framework in Futureverse - Easy!",
    author = "Henrik Bengtsson",
  location = "useR! 2024, Salzburg, Austria",
      date = "2024-07-09",
  duration = "20 minutes",
      urls = c(HTML = "https://henrikbengtsson.github.io/talk-user2024-future.mirai/#/", PDF = "https://raw.githubusercontent.com/HenrikBengtsson/talk-user2024-future.mirai/main/BengtssonH_20240709-future.mirai-useR2024.pdf")
)
```


```{r}
#| echo: false
talk(
     title = "Futureverse - A Unifying Parallelization Framework in R for Everyone",
    author = "Henrik Bengtsson",
  location = "Edmonton R User Group Meetup (YEGRUG) (virtual)",
      date = "2023-05-22",
  duration = "60 minutes",
      urls = c(HTML = "https://docs.google.com/presentation/d/e/2PACX-1vQfbnVRHZhIkEAd3_pNG14N5JQqE0jqCohSq-m-uWAcA7StF-BuHdOz0IGDhcRI3K681DxoXoqA7pwp/pub?start=true&loop=false&delayms=60000", PDF = "https://www.jottr.org/presentations/yegrug2023/BengtssonH_20230522-Futureverse-YEGRUG.pdf", Video = "https://www.youtube.com/watch?v=6Dp6zMelrmg", "Blog post" = "https://www.jottr.org/2023/05/22/future-yegrug-2023-slides/")
)
```


```{r}
#| echo: false
talk(
     title = "Futureverse: Profile Parallel Code",
    author = "Henrik Bengtsson",
  location = "useR! 2022, worldwide (virtual)",
      date = "2022-06-22",
  duration = "25 minutes",
      urls = c(HTML = "https://docs.google.com/presentation/d/e/2PACX-1vTnpyj7qvyKr-COHaJAYjoGveoOJPYrstTmvC4farFk2vdwWb8O79kA5tn7klTS67_uoJJdKFPgKNql/pub?start=true&loop=false&delayms=60000&slide=id.gf778290f24_0_165", PDF = "https://www.jottr.org/presentations/useR2022/BengtssonH_20220622-Future-useR2022.pdf", Video = "https://www.youtube.com/watch?v=_lrPgNqT3SM&t=2528s", "Blog post" = "https://www.jottr.org/2022/06/23/future-user2022-slides/")
)
```


```{r}
#| echo: false
talk(
     title = "Future - Simple, Scalable Parallelization in R for the Biomedical Community",
    author = "Henrik Bengtsson",
  location = "CZI EOSS 2021, worldwide (virtual)",
      date = "2021-11-02",
  duration = "10 minutes",
      urls = c(HTML = "https://docs.google.com/presentation/d/18gxBd5Bgn0GNDyl5MlCt_s7b6gTUEcJV9c2xSLC11Nk/view#slide=id.gf778290f24_0_165", PDF = "", Video = "", "Blog post" = "")
)
```




```{r}
#| echo: false
talk(
     title = "Future: A Simple, Extendable, Generic Framework for Parallel Processing in R",
    author = "Henrik Bengtsson",
  location = "European Bioconductor Meeting 2020, worldwide (virtual)",
      date = "2020-12-19",
  duration = "35 minutes",
      urls = c(HTML = "https://docs.google.com/presentation/d/e/2PACX-1vTVyeaWRH251Pm8BfrlH1yK4Bd_YojEmo1I0VFxkoehnoxYJXglLdDf5T6_bTDv7lFJjwrXNYFBtfHT/pub?start=false&loop=false&delayms=10000", PDF = "https://www.jottr.org/presentations/EuroBioc2020/BengtssonH_20201218-futures-EuroBioc2020.pdf", Video = "https://www.youtube.com/watch?v=Ph8jItU7Dlo", "Blog post" = "https://www.jottr.org/2020/12/19/future-eurobioc2020-slides/")
)
```


```{r}
#| echo: false
talk(
     title = "Future: Simple, Friendly Parallel Processing for R",
    author = "Henrik Bengtsson",
  location = "New York Open Statistical Programming Meetup, worldwide (virtual)",
      date = "2020-11-12",
  duration = "67 minutes",
      urls = c(HTML = "https://docs.google.com/presentation/d/1E2Gcm33_uMrhQL7jLzodlMXUefnSshHUdYsoXWAkFYE/edit?usp=sharing", PDF = "https://www.jottr.org/presentations/NYCMeetup2020/BengtssonH_20191109-futures-NYC.pdf", Video = "https://youtu.be/2ZlpFkFMy7E?t=630", "Blog post" = "https://www.jottr.org/2020/11/12/future-nycmeetup-slides/")
)
```


```{r}
#| echo: false
talk(
     title = "Progressr: An Inclusive, Unifying API for Progress Updates",
    author = "Henrik Bengtsson",
  location = "e-Rum 2020, worldwide (virtual)",
      date = "2020-06-17",
  duration = "15 minutes",
      urls = c(HTML = "https://docs.google.com/presentation/d/11RymPwL90rPc0dQwpNCnw5KQC_76tuDK7uB7rq26oIg/present#slide=id.g88962cfdb7_0_0", PDF = "https://www.jottr.org/presentations/eRum2020/BengtssonH_20200617-progressr-An_Inclusive,_Unifying_API_for_Progress_Updates.pdf", Video = "https://www.youtube.com/watch?v=NwVOvfpGq4o&t=3001s", "Blog post" = "https://www.jottr.org/2020/07/04/progressr-erum2020-slides/")
)
```


```{r}
#| echo: false
talk(
     title = "Future: Simple Async, Parallel & Distributed Processing in R Why and What’s New?",
    author = "Henrik Bengtsson",
  location = "rstudio::conf 2020, San Francisco, California, USA",
      date = "2020-01-29",
  duration = "18 minutes",
      urls = c(HTML = "https://docs.google.com/presentation/d/1Wn5S91UGIOrc4IyXoV074ij5vGF8I0Km0tCfintyIa4/present?includes_info_params=1&eisi=CM2mhIXwsecCFQyuJgodBQAJ8A#slide=id.p", PDF = "https://www.jottr.org/presentations/rstudioconf2020/BengtssonH_20200129-future-rstudioconf2020.pdf", Video = "https://resources.rstudio.com/rstudio-conf-2020/future-simple-async-parallel-amp-distributed-processing-in-r-whats-next-henrik-bengtsson", "Blog post" = "https://www.jottr.org/2020/02/01/future-rstudioconf2020-slides/")
)
```


```{r}
#| echo: false
talk(
     title = "Future: Simple Parallel and Distributed Processing in R",
    author = "Henrik Bengtsson",
  location = "useR! 2019, Toulouse, France",
      date = "2019-07-12",
  duration = "15 minutes",
      urls = c(HTML = "https://docs.google.com/presentation/d/e/2PACX-1vQDLsnzhfp03zAf-BG69mnwO6nqGyLP9Zuj5ShW0gbewY955wop6KO5bidbWxtrIydFj7lznwi1op__/pub?start=false&loop=false&delayms=60000", PDF = "https://www.jottr.org/presentations/useR2019/BengtssonH_20190712-future-useR2019.pdf", Video = "https://www.youtube.com/watch?v=4B3wPFL_Syo&list=PL4IzsxWztPdliwImi5JLBC4BrvqxG-vcA&index=69", "Blog post" = "https://www.jottr.org/2019/07/12/future-user2019-slides/")
)
```


```{r}
#| echo: false
talk(
     title = "Future: Friendly Parallel Processing in R for Everyone",
    author = "Henrik Bengtsson",
  location = "satRday LA 2019, Los Angeles, USA",
      date = "2019-04-06",
  duration = "45 minutes",
      urls = c(HTML = "https://www.jottr.org/presentations/satrdayla2019/bengtssonh_20190406-satrdayla2019,flat", PDF = "https://www.jottr.org/presentations/satRdayLA2019/BengtssonH_20190406-SatRdayLA2019,flat.pdf", Video = "https://www.youtube.com/watch?v=KP3pgLfKr00&list=PLQRHxIa9tfRvXYyaVS77zshvD0i17Y60s", "Blog post" = "https://www.jottr.org/2019/05/16/future-satrdayla2019-slides/")
)
```


```{r}
#| echo: false
talk(
     title = "Future: Friendly Parallel Processing in R for Everyone",
    author = "Henrik Bengtsson",
  location = "satRday Paris 2019, Paris, France",
      date = "2019-02-23",
  duration = "50 minutes",
      urls = c(HTML = "https://www.jottr.org/presentations/satrdayparis2019/bengtssonh_20190223-satrdayparis2019", PDF = "https://www.jottr.org/presentations/satRdayParis2019/BengtssonH_20190223-SatRdayParis2019.pdf", "Blog post" = "https://www.jottr.org/2019/03/07/future-satrdayparis2019-slides/
")
)
```


```{r}
#| echo: false
talk(
     title = "Future: Parallel & Distributed Processing in R for Everyone",
    author = "Henrik Bengtsson",
  location = "eRum 2018, Budapest, Hungary",
      date = "2018-05-16",
  duration = "20 minutes",
      urls = c(HTML = "https://www.jottr.org/presentations/erum2018/bengtssonh_20180516-erum2018", PDF = "https://www.jottr.org/presentations/eRum2018/BengtssonH_20180516-eRum2018.pdf", Video = "https://www.youtube.com/watch?v=doa7avxbptQ", "Blog post" = "https://www.jottr.org/2018/06/18/future-erum2018-slides/
")
)
```



```{r}
#| echo: false
talk(
     title = "Futures in R: Atomic Building Blocks for Asynchronous Evaluation",
    author = "Henrik Bengtsson",
  location = "R Consortium, Distributed Computing Working Group, worldwide (virtual)",
      date = "2017-05-11",
  duration = "60 minutes",
      urls = c(PDF = "https://wiki.r-consortium.org/images/2/25/BengtssonH_20170511-future%2CRConsortium%2Cflat.pdf", "Event" = "https://wiki.r-consortium.org/view/Distributed_Computing_Working_Group#05.2F11.2F2017")
)
```


```{r}
#| echo: false
talk(
     title = "A Future for R",
    author = "Henrik Bengtsson",
  location = "useR! 2016, Stanford, California, USA",
      date = "2016-06-28",
  duration = "18 minutes",
      urls = c(HTML = "http://www.aroma-project.org/share/presentations/BengtssonH_20160628-useR2016/BengtssonH_20160628-A_Future_for_R,useR2016.html", PDF = "http://www.aroma-project.org/share/presentations/BengtssonH_20160628-useR2016/BengtssonH_20160628-A_Future_for_R,useR2016,flat.pdf", Video = "https://www.youtube.com/watch?v=K8KYi9AFRlk", "Blog post" = "https://www.jottr.org/2016/07/02/future-user2016-slides/")
)
```

