---
title: Tutorials
description: Tutorials on Using Futures
preview: images/site_preview.png
format: html
---


<style>
/* Borrowed from https://www.tidyverse.org/blog/ */
.listItem {
 display:flex;
 justify-content:flex-start;
 display:-ms-flexbox;
 -ms-flex-pack:start;
 display:-webkit-box;
 display:-webkit-flex;
 -webkit-justify-content:flex-start;
 margin-bottom:30px
}
.listItem .itemImage {
 flex-shrink:0;
 width:150px;
 height:150px;
 margin:0 30px 15px 0;
 background-size:contain;
 background-position:center
}
.listItem .itemImage img {
    width: 100%;
    max-height: 100%;
    object-fit: cover
}
.listItem .itemDetails {
 width:100%;
 font-size:.875rem;
 line-height:20px
}
.listItem .itemDetails .itemHeader {
 display:flex;
 justify-content:space-between;
 display:-ms-flexbox;
 -ms-flex-pack:justify;
 display:-webkit-box;
 display:-webkit-flex;
 -webkit-justify-content:space-between;
 align-items:flex-start;
 line-height:30px;
 margin-bottom:3px
}
.listItem .itemDetails .itemHeader .itemTitle {
 font-size:20px;
 display:block
}
.listItem .itemDetails .itemHeader .itemActions {
 flex-shrink:0;
 height:30px
}
.listItem .itemDetails .itemMeta .itemDescription {
 margin-bottom:.375rem;
 white-space:pre-line
}
.listItem .itemDetails .itemMeta .itemDate,
.listItem .itemDetails .itemMeta .itemInfo {
 font-size:.875rem;
 color:grey;
}
.listItem .itemDetails .itemMeta .itemInfo li {
 margin-bottom: 0.1em;
}
.listItem .itemDetails .itemMeta .itemDate .created,
.listItem .itemDetails .itemMeta .itemDate .updated,
.listItem .itemDetails .itemMeta .itemInfo .created,
.listItem .itemDetails .itemMeta .itemInfo .updated {
 display:inline-block
}
.listItem .itemDetails .itemMeta .itemDate .created,
.listItem .itemDetails .itemMeta .itemInfo .created {
 padding-right:20px
}
.listItem .itemDetails .itemMeta .itemInfo .forkedFrom {
 display:inline-block
}
.listItem .itemDetails .itemMeta .itemInfo .updated {
 padding-right:20px
}
</style>


<div class="listItem">
 <div class="itemDetails">
  <div class="itemHeader">
   <div class="itemTitle"><a href="https://henrikbengtsson.github.io/futureverse-tutorial-raukr2025/">Futureverse: A Unifying Parallelization Framework in R for Everyone (RaukR 2025)</a>
   </div>
  </div>
  <div class="itemMeta">
   <div class="author">Henrik Bengtsson</div>
   <div class="itemInfo">
Location: RaukR Summer School 2025, R Beyond the Basics, Visby, Sweden, June 9-19, 2025
   </div>
   <div class="itemDate">2025-06-12</div>
  </div>
 </div>
</div>


<div class="listItem">
 <div class="itemDetails">
  <div class="itemHeader">
   <div class="itemTitle">Futureverse: A Unifying Parallelization Framework in R for Everyone (useR! 2024)</a>
   </div>
  </div>
  <div class="itemMeta">
   <div class="author">Henrik Bengtsson</div>
   <div class="itemInfo">
Location: useR! 2024, Salzburg, Austria, June 8-12, 2024
   </div>
   <div class="itemDate">2024-07-08</div>
  </div>
 </div>
</div>


<div class="listItem">
 <div class="itemDetails">
  <div class="itemHeader">
   <div class="itemTitle"><a href="https://henrikbengtsson.github.io/future-tutorial-user2024/">Futureverse: Friendly Parallelization in R (useR! 2024)</a>
   </div>
  </div>
  <div class="itemMeta">
   <div class="author">Henrik Bengtsson</div>
   <div class="itemInfo">
Location: useR! 2024, Salzburg, Austria, June 8-12, 2024
   </div>
   <div class="itemDate">2024-07-08</div>
  </div>
 </div>
</div>


<div class="listItem">
 <div class="itemDetails">
  <div class="itemHeader">
   <div class="itemTitle"><a href="https://henrikbengtsson.github.io/future-tutorial-raukr2024/">Futureverse: A Unifying Parallelization Framework in R for Everyone (RaukR 2024)</a>
   </div>
  </div>
  <div class="itemMeta">
   <div class="author">Henrik Bengtsson</div>
   <div class="itemInfo">
Location: RaukR Summer School 2024, Advanced R for Bioinformatics, Visby, Sweden, June 10-20, 2024
   </div>
   <div class="itemDate">2024-06-12, 2024-06-17</div>
  </div>
 </div>
</div>


<div class="listItem">
 <div class="itemDetails">
  <div class="itemHeader">
   <div class="itemTitle"><a href="https://henrikbengtsson.github.io/course-stanford-futureverse-2023/">Futureverse - A Unifying Parallelization Framework in R for Everyone: STATS/BIODS 352: Topics in Computing for Data Science, Bridging Methodology and Practice, Stanford University, 2023</a>
   </div>
  </div>
  <div class="itemMeta">
   <div class="author">Henrik Bengtsson</div>
   <div class="itemInfo">
Location: Stanford University, April 20 & 27, 2023
   </div>
   <div class="itemDate">2023-04-27</div>
  </div>
 </div>
</div>


<div class="listItem">
 <div class="itemDetails">
  <div class="itemHeader">
   <div class="itemTitle"><a href="https://henrikbengtsson.github.io/future-tutorial-user2022/">An Introduction to Futureverse for Parallel Processing in R (useR! 2022)</a>
   </div>
  </div>
  <div class="itemMeta">
   <div class="author">Henrik Bengtsson</div>
   <div class="itemInfo">
Location: useR! 2022 conference, online, June 20-24, 2022
   </div>
   <div class="itemDate">2022-06-20</div>
  </div>
 </div>
</div>
